export const FETCH_ASSETS = 'FETCH_ASSETS';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';
export const SET_SELECTED = 'SET_SELECTED';
export const SET_ASSET_CONTRACT_ADDRESS = 'SET_ASSET_CONTRACT_ADDRESS';